#!/usr/bin/node
const { exec } = require("child_process");
const args = process.argv.slice(2);
const url = args[0];
const hostWs = args[2];
function wsChecker(url, host) {
    return new Promise(resolve => {
        exec(
            `curl -I ${url} -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: ${host}"`,
            (error, stdout, stderr) => {
                if (error) {
                    resolve(false);
                } else if (stderr) {
                    resolve(false);
                }
                if (stdout.includes("Upgrade: websocket")) {
                    console.log(
                        `Output:\n${stdout}\n[+] Success upgrade to Websocket`
                    );
                } else {
                    console.log(
                        `Output:\n${stdout}\n[+] Failed upgrade to Websocket`
                    );
                }
            }
        );
    });
}

(async () => {
    if (url && args[1] === "-hws" && hostWs) {
        await wsChecker(url, hostWs);
        process.exit(0);
    } else if (args[0] === "-h") {
        const info = `"HCheck" is a host bug checking tool for tunneling via HTTP Websocket.
Usage: ./hcheck <url> -hws <host_ws>

Options:
  <url> : The URL you want to check
  -hws <host_ws> : Websocket Host (<host_ws>) that supports websockets

Example: ./hcheck http://example.com -hws ex.websocket.org`;
        console.log(info);
    } else {
        console.log(`Invalid Command!\nTry './hcheck -h' for information`);
    }
})();
